In [33]:
import os
import random
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import f1_score

In [ ]:
test_set = pd.read_csv("../../../data/test_set.csv")
# Convertir a numpy arrays
x_test = test_set.drop(columns=['target_trend']).values
y_test = test_set['target_trend'].values    
y_pred = test_set['trend_d0'].values

In [35]:
# Reporte completo: precisión, recall y F1 por clase
print("Test:")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4))

Test:
[[50  3  0]
 [ 3  8  2]
 [ 0  2 63]]
              precision    recall  f1-score   support

          -1     0.9434    0.9434    0.9434        53
           0     0.6154    0.6154    0.6154        13
           1     0.9692    0.9692    0.9692        65

    accuracy                         0.9237       131
   macro avg     0.8427    0.8427    0.8427       131
weighted avg     0.9237    0.9237    0.9237       131

